name: CMake build
on: [push, pull_request]
jobs:
  cmake-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: |
        sudo apt install -y libboost-all-dev
    - name: Compile
      env:
        CXXFLAGS: -O2
      run: |
        cmake -DBOOST_ROOT=/usr .
        make -j 2
    - name: Test
      run: |
        ./test-suite/quantlib-test-suite --log_level=message
  cmake-win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: |
        $Url = "https://sourceforge.net/projects/boost/files/boost-binaries/1.75.0/boost_1_75_0-msvc-14.2-64.exe"
        (New-Object System.Net.WebClient).DownloadFile($Url, "$env:TEMP\boost.exe")
        Start-Process -Wait -FilePath "$env:TEMP\boost.exe" "/SILENT","/SP-","/SUPPRESSMSGBOXES","/DIR=C:\local\boost-1.75.0"
    - name: Compile
      env:
        BOOST_ROOT: C:\local\boost-1.75.0
      run: |
        cmake .
        cmake --build . --config Release
    - name: Test
      run: |
        .\test-suite\Release\quantlib-test-suite --log_level=message
  cmake-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: |
        brew install boost
    - name: Compile
      env:
        CXXFLAGS: -O2 -std=c++11 -stdlib=libc++ -mmacosx-version-min=10.9
      run: |
        cmake .
        make -j 2
    - name: Test
      run: |
        ./test-suite/quantlib-test-suite --log_level=message
